# https://taskfile.dev

version: '3'

vars:
  REPOSITORY: ghcr.io/adrianliechti/loop-pocketbase

tasks:
  publish:
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 --push --tag {{.REPOSITORY}} .
  
  start:
    cmds:
      - docker compose up